import { NextRequest } from "next/server";
import PDFDocument from "pdfkit";
import { getAdminServices } from "@/lib/firebase/admin";
import { BillingDocument } from "@/lib/types";

export const dynamic = "force-dynamic";

export async function GET(req: NextRequest, context: { params: Promise<{ id: string }> }) {
  try {
    const token = req.headers.get("authorization")?.replace("Bearer ", "");
    if (!token) return new Response("Missing token", { status: 401 });
    const { auth, db } = getAdminServices();
    const decoded = await auth.verifyIdToken(token);
    const roleDoc = await db.collection("users").doc(decoded.uid).get();
    if (roleDoc.get("role") !== "admin") {
      return new Response("Forbidden", { status: 403 });
    }

    const { id } = await context.params;

    const docSnap = await db.collection("documents").doc(id).get();
    if (!docSnap.exists) return new Response("Not found", { status: 404 });
    const data = docSnap.data() as BillingDocument;

    const branding = await db.collection("settings").doc("branding").get();
    const brandUrl = branding.data()?.url as string | undefined;

    const pdf = new PDFDocument({ margin: 48 });
    const chunks: Buffer[] = [];
    pdf.on("data", (chunk) => chunks.push(chunk));

    pdf.fillColor("#c1121f").fontSize(22).text(`Imagicity ${data.kind === "invoice" ? "Invoice" : "Quotation"}`, {
      align: "left",
    });
    pdf.moveDown(0.5);
    pdf.fontSize(10).fillColor("#444").text(`Number: ${data.number}`);
    pdf.text(`Issue date: ${data.issueDate}`);
    if (data.dueDate) pdf.text(`Due date: ${data.dueDate}`);
    pdf.text(`Status: ${data.status.toUpperCase()}`);
    pdf.moveDown();

    pdf.fontSize(12).fillColor("#c1121f").text("Seller", { continued: false });
    pdf.fillColor("#222").fontSize(10).text(data.seller.name);
    pdf.text(data.seller.address);
    if (data.seller.gstin) pdf.text(`GSTIN: ${data.seller.gstin}`);

    pdf.moveDown();
    pdf.fillColor("#c1121f").fontSize(12).text("Bill to");
    pdf.fillColor("#222").fontSize(10).text(data.buyer.name);
    pdf.text(data.buyer.address);
    if (data.buyer.gstin) pdf.text(`GSTIN: ${data.buyer.gstin}`);

    pdf.moveDown();
    pdf.fillColor("#c1121f").fontSize(12).text("Line items");
    pdf.fillColor("#222").fontSize(10);
    data.items.forEach((item, idx) => {
      const lineTotal = item.quantity * item.unitPrice;
      const tax = data.gstEnabled ? ((item.gstRate ?? 0) / 100) * lineTotal : 0;
      pdf.text(
        `${idx + 1}. ${item.description} — Qty ${item.quantity} × ₹${item.unitPrice.toFixed(2)} | GST ${item.gstRate ?? 0}% | Line ₹${(
          lineTotal + tax
        ).toFixed(2)}`
      );
    });

    pdf.moveDown();
    pdf.fillColor("#222").text(`Place of supply: ${data.placeOfSupply ?? "NA"}`);
    pdf.text(`GST applicable: ${data.gstEnabled ? "Yes" : "No"}`);
    if (data.voidReason) pdf.text(`Void reason: ${data.voidReason}`);

    pdf.moveDown();
    pdf.fontSize(12).fillColor("#c1121f").text("Totals", { underline: true });
    pdf.fillColor("#222").fontSize(11);
    pdf.text(`Subtotal: ₹${(data.subtotal ?? 0).toFixed(2)}`);
    pdf.text(`Tax: ₹${(data.totalTax ?? 0).toFixed(2)}`);
    pdf.text(`Total payable: ₹${(data.total ?? 0).toFixed(2)}`);

    if (brandUrl) {
      pdf.moveDown();
      pdf.fontSize(9).fillColor("#777").text(`Brand asset: ${brandUrl}`);
    }

    pdf.moveDown();
    pdf.fontSize(8).fillColor("#999").text("Generated by Imagicity billing platform - server-side PDF export.");
    pdf.end();

    const pdfBuffer: Buffer = await new Promise((resolve) => {
      pdf.on("end", () => resolve(Buffer.concat(chunks)));
    });

    const pdfBytes = new Uint8Array(pdfBuffer.byteLength);
    pdfBytes.set(pdfBuffer);
    const pdfBlob = new Blob([pdfBytes], { type: "application/pdf" });

    return new Response(pdfBlob, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `inline; filename=${data.number}.pdf`,
      },
    });
  } catch (error) {
    console.error(error);
    return new Response("Failed to generate PDF", { status: 500 });
  }
}
